# Generated by Django 3.2.14 on 2022-07-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hta_platform', '0014_auto_20220714_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.university')),
            ],
        ),
    ]
