# Generated by Django 3.2.14 on 2022-09-04 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0017_alter_studentexam_unique_together'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(6.0)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
