# Generated by Django 3.2.14 on 2022-09-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deadline',
            field=models.DateTimeField(default='2022-10-10 9:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
