# Generated by Django 3.2.9 on 2022-03-10 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0007_auto_20220303_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='obligatory_mark',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(6.0)]),
            preserve_default=False,
        ),
    ]
