# Generated by Django 3.2.9 on 2022-03-10 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0008_student_obligatory_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='obligatory_mark',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
    ]
