# Generated by Django 3.2.14 on 2022-07-12 10:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0010_university_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('obligatory_coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(6.0)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hta_platform.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.student')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hta_platform.exam')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='exams',
            field=models.ManyToManyField(through='hta_platform.ProgramExam', to='hta_platform.Exam'),
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.university'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hta_platform.university'),
        ),
        migrations.AddField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(through='hta_platform.StudentExam', to='hta_platform.Exam'),
        ),
    ]
