# Generated by Django 3.2.14 on 2022-07-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0012_auto_20220714_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
