# Generated by Django 3.2.14 on 2022-07-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hta_platform', '0013_delete_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programexam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='programexam',
            name='program',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramExam',
        ),
    ]
