# Generated by Django 3.2.14 on 2022-07-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('programs', '0002_auto_20220720_1632'),
        ('hta_platform', '0014_auto_20220714_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(through='hta_platform.StudentExam', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.exam'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
