# Generated by Django 3.2.14 on 2022-09-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('hta_platform', '0016_student_bio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together={('student', 'exam')},
        ),
    ]
