# Generated by Django 3.2.14 on 2022-07-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('programs', '0002_auto_20220720_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='exams',
            field=models.ManyToManyField(null=True, through='programs.ProgramExam', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='programexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
    ]
