# Generated by Django 3.2.14 on 2022-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('programs', '0003_auto_20220720_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='exams',
            field=models.ManyToManyField(through='programs.ProgramExam', to='exams.Exam'),
        ),
    ]
